### ISSUE TITLE
本地运行报错

### ISSUE THREAD

**Issue by Jerrodly** [RootLinkFE/roothub#2]
安装完所有依赖，运行npm run dev的时候报错：
roothub/server/controller/blocks.js:15
let blocks = data.list?.blocks
                             ^

SyntaxError: Unexpected token .
    at Module._compile (internal/modules/cjs/loader.js:872:18)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10)
    at Module.load (internal/modules/cjs/loader.js:790:32)
    at Function.Module._load (internal/modules/cjs/loader.js:703:12)
    at Module.require (internal/modules/cjs/loader.js:830:19)
    at require (internal/modules/cjs/helpers.js:68:18)

**Comment by giscafer** [comment]
node.js 版本问题吧，可选链是ES7特性。建议node.js v14+
